In [1]:
import numpy as np


In [3]:
list(range(0,10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
#creación de arrays
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#zeros
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(4)

array([0.49243438, 0.88926925, 0.14527655, 0.62161947])

In [19]:
np.random.rand(4,4)

array([[0.24986962, 0.76779748, 0.73557743, 0.30848549],
       [0.49385745, 0.14909068, 0.05280868, 0.65399627],
       [0.59665132, 0.09611069, 0.49913503, 0.48438688],
       [0.13674051, 0.11843007, 0.21643847, 0.22757847]])

In [20]:
np.random.randint(1,15)

6

In [21]:
np.random.randint(1,15,(10,5))

array([[10,  3, 13, 14, 14],
       [ 4,  6,  4,  6,  6],
       [ 5, 12,  5,  5,  1],
       [ 5, 10,  5,  4, 12],
       [13,  9, 12, 13,  6],
       [ 8,  5,  9, 11,  7],
       [10,  2,  2, 13,  9],
       [11,  6,  3, 11,  5],
       [ 2,  9,  8, 10, 14],
       [12,  5,  2, 12, 12]])