In [1]:
import numpy as np

In [3]:
arr=np.linspace(1,10,10, dtype ='int8' )
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
indice_cond=arr>5

In [5]:
arr[indice_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [7]:
arr[(indice_cond ) & (arr<9)]

array([6, 7, 8], dtype=int8)