In [1]:
import numpy as np

In [4]:
scalar = np.array(42)
print(scalar)

42


In [6]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3