In [1]:
import numpy as np

In [3]:
arr=np.random.randint(1,20,10)

In [4]:
matriz=arr.reshape(2,5)
matriz

array([[ 5, 13, 12, 11,  9],
       [ 1, 15,  3, 13,  3]])

In [5]:
arr.max()

15

In [7]:
matriz.max(1)

array([13, 15])

In [9]:
#muestra la posicion donde esta la valor máximo
arr.argmax(0)

6

In [10]:
matriz.argmax(0)

array([0, 1, 0, 1, 0], dtype=int64)

In [16]:
arr.min()


1

In [12]:
arr.min(0)

1

In [17]:
arr.ptp()

14

In [19]:
np.percentile(arr,50)

10.0

In [20]:
arr

array([ 5, 13, 12, 11,  9,  1, 15,  3, 13,  3])

In [22]:
#para ordenar de mayor a menor
arr.sort()
arr

array([ 1,  3,  3,  5,  9, 11, 12, 13, 13, 15])

In [23]:
np.median(arr)

10.0

In [24]:
np.std(arr)

4.801041553663121

In [26]:
np.var(arr)

23.05

In [27]:
#promedio
np.mean(arr)

8.5

In [32]:
a= np.array([[1,2],[3,4]])
p= np.array([[5,6],[7,8]])
a

array([[1, 2],
       [3, 4]])

In [33]:
np.concatenate((a,p), axis =0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])