In [1]:
import numpy as np


In [4]:
lista = [1,2]

lista

[1, 2]

In [8]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2 = arr.copy()

In [11]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
1/arr

C:\Temp\ipykernel_2860\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
np.eye(0,10)

array([], shape=(0, 10), dtype=float64)